# Generated by Django 6.0.7 on 2026-07-30 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('trip_start', models.DateTimeField()),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, default=dict)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('driver_name', models.CharField(default='Sample Driver', max_length=120)),
                ('driver_id', models.CharField(default='DRV-0001', max_length=40)),
                ('carrier_name', models.CharField(default='Sample Carrier Inc.', max_length=255)),
                ('main_office_address', models.CharField(default='123 Logistics Way, Springfield, USA', max_length=255)),
                ('truck_number', models.CharField(default='Truck 123', max_length=40)),
                ('trailer_number', models.CharField(default='Trailer 20544', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSheetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('total_miles_today', models.FloatField(default=0)),
                ('segments', models.JSONField(default=list)),
                ('total_off_duty', models.FloatField(default=0)),
                ('total_sleeper', models.FloatField(default=0)),
                ('total_driving', models.FloatField(default=0)),
                ('total_on_duty_not_driving', models.FloatField(default=0)),
                ('cycle_hours_used_recap', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index'],
                'unique_together': {('trip', 'day_index')},
            },
        ),
    ]
